db:
  host: '192.168.0.101'
  port: 3306
  user: 'dev'
  password: 'password'
  name: 'chat'

consumer:
  brokers: ['192.168.0.105:9092']
  topic: 'store.chat.message'
  group_id: 'consumer-chat-group'

cache:
  address: '192.168.0.105'
  port: ':6379'
  password: 'Awesome85**'
  db: 0
  pool_size: 25
  minimum_idle_connections: 10
  maximum_retries: 1
  message_key_format: 'message.for.%s'
  token_key_format: 'token.%s'

firebase:
  function_address: 'https://us-central1-superheromatch.cloudfunctions.net/newMessage'
  content_type: 'application/json'

health:
  port: ':8040'
  shutdown_endpoint: '/api/v1/consumer_superhero_chat_health/shutdown'
  content_type: 'application/json'